name: Deploy Mujay to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write # Ensure this is 'write'
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      # Install dependencies
      - name: Install Dependencies
        run: bun install

      # Build the static site
      - name: Build Static Site
        env:
          DESKTOP: 1
        run: bun run build

      # Create .nojekyll file to disable Jekyll
      - name: Create .nojekyll
        run: touch build/.nojekyll

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          # Use the deploy_key input instead of github_token for SSH authentication
          # Reference the SECRET NAME that stores your PRIVATE KEY
          deploy_key: ${{ secrets.SHA256:lpTEjhaVXun/KNqtemSDIjxyZM4KbhxgHIalYrBrp/c }}
          publish_dir: ./build
          publish_branch: gh-pages
          # Optionally, specify the repository if it's different from the source
          # external_repository: <your-username>/<your-repo>
