name: Deploy Mujay to GitHub Pages

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      # Install dependencies
      - name: Install Dependencies
        run: bun install

      # Build the static site
      - name: Build Static Site
        env:
          DESKTOP: 1
        run: bun run build

      # Create .nojekyll file to disable Jekyll
      - name: Create .nojekyll
        run: touch build/.nojekyll

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.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 }}
          publish_dir: ./build
          publish_branch: gh-pages
